/**
 * Config validation test — catches invalid OpenClaw config keys before deployment.
 *
 * OpenClaw rejects unknown config keys and exits with code 1. This test validates
 * the config structure generated by openclaw-config.js (the SAME module used by
 * agentcore-contract.js at runtime) so drift between test and production is impossible.
 *
 * Run: cd bridge && node --test config-validation.test.js
 */

const { describe, it } = require("node:test");
const assert = require("node:assert/strict");
const { generateOpenClawConfig, PROXY_PORT, OPENCLAW_PORT, SUBAGENT_MODEL_NAME } = require("./openclaw-config");

// --- Known valid OpenClaw config keys (update when OpenClaw schema changes) ---
// Source: `openclaw doctor --fix` output + OpenClaw docs

const VALID_TOP_LEVEL_KEYS = new Set([
  "models",
  "agents",
  "tools",
  "skills",
  "gateway",
  "channels",
  "controlUi",
]);

const VALID_AGENTS_DEFAULTS_KEYS = new Set([
  "model",
  "subagents",
  "sandbox",
]);

const VALID_SUBAGENTS_KEYS = new Set([
  "model",
  "maxConcurrent",
  "runTimeoutSeconds",
  "archiveAfterMinutes",
  "sandbox",
]);

const VALID_TOOLS_KEYS = new Set([
  "profile",
  "deny",
  "allow",
]);

const VALID_GATEWAY_KEYS = new Set([
  "mode",
  "port",
  "trustedProxies",
  "auth",
  "controlUi",
  "bind",
]);

const VALID_SKILLS_KEYS = new Set([
  "allowBundled",
  "load",
]);

// --- Validation helper ---

function validateKeys(obj, validKeys, path) {
  const unknownKeys = Object.keys(obj).filter((k) => !validKeys.has(k));
  assert.deepStrictEqual(
    unknownKeys,
    [],
    `Unknown keys at ${path}: ${unknownKeys.join(", ")}. ` +
      `Valid keys: ${[...validKeys].join(", ")}`,
  );
}

// --- Tests ---

describe("OpenClaw config validation", () => {
  // Generate using the SAME function as agentcore-contract.js — no duplicate config.
  const config = generateOpenClawConfig({ gatewayToken: "test-token" });

  it("generates valid JSON", () => {
    const json = JSON.stringify(config, null, 2);
    assert.ok(json.length > 0);
    const parsed = JSON.parse(json);
    assert.ok(parsed);
  });

  it("has only valid top-level keys", () => {
    validateKeys(config, VALID_TOP_LEVEL_KEYS, "config");
  });

  it("has only valid agents.defaults keys (no runTimeoutSeconds/maxToolUses)", () => {
    validateKeys(config.agents.defaults, VALID_AGENTS_DEFAULTS_KEYS, "agents.defaults");
  });

  it("does NOT have runTimeoutSeconds at agents.defaults level", () => {
    assert.ok(
      !("runTimeoutSeconds" in config.agents.defaults),
      "runTimeoutSeconds must NOT be at agents.defaults — OpenClaw rejects it. " +
        "Move to agents.defaults.subagents if needed.",
    );
  });

  it("does NOT have maxToolUses at agents.defaults level", () => {
    assert.ok(
      !("maxToolUses" in config.agents.defaults),
      "maxToolUses must NOT be at agents.defaults — OpenClaw rejects it. " +
        "Move to agents.defaults.subagents if needed.",
    );
  });

  it("has only valid subagents keys", () => {
    validateKeys(config.agents.defaults.subagents, VALID_SUBAGENTS_KEYS, "agents.defaults.subagents");
  });

  it("has only valid tools keys", () => {
    validateKeys(config.tools, VALID_TOOLS_KEYS, "tools");
  });

  it("has only valid gateway keys", () => {
    validateKeys(config.gateway, VALID_GATEWAY_KEYS, "gateway");
  });

  it("has only valid skills keys", () => {
    validateKeys(config.skills, VALID_SKILLS_KEYS, "skills");
  });

  it("tools.profile is a valid profile name", () => {
    const validProfiles = new Set(["minimal", "coding", "messaging", "full"]);
    assert.ok(
      validProfiles.has(config.tools.profile),
      `Invalid tools.profile: "${config.tools.profile}". Valid: ${[...validProfiles].join(", ")}`,
    );
  });

  it("skills.allowBundled is an array", () => {
    assert.ok(
      Array.isArray(config.skills.allowBundled),
      "skills.allowBundled must be an array, not a boolean",
    );
  });

  it("sandbox mode is off", () => {
    assert.strictEqual(config.agents.defaults.sandbox.mode, "off");
  });

  it("agents.defaults has exactly model, sandbox, subagents", () => {
    const topLevelKeys = Object.keys(config.agents.defaults).sort();
    assert.deepStrictEqual(topLevelKeys, ["model", "sandbox", "subagents"]);
  });

  it("exports correct port constants", () => {
    assert.strictEqual(PROXY_PORT, 18790);
    assert.strictEqual(OPENCLAW_PORT, 18789);
  });

  it("exports correct subagent model name", () => {
    assert.strictEqual(SUBAGENT_MODEL_NAME, "bedrock-agentcore-subagent");
  });

  it("gateway auth is token mode", () => {
    assert.strictEqual(config.gateway.auth.mode, "token");
  });

  // --- Sub-agent requirements ---

  it("controlUi.enabled is true (required for sub-agent sessions)", () => {
    assert.strictEqual(
      config.gateway.controlUi.enabled,
      true,
      "controlUi.enabled must be true — sub-agents connect via the control API",
    );
  });

  it("dangerouslyDisableDeviceAuth is true (sub-agents skip device pairing)", () => {
    assert.strictEqual(
      config.gateway.controlUi.dangerouslyDisableDeviceAuth,
      true,
      "dangerouslyDisableDeviceAuth must be true for sub-agents to connect without pairing",
    );
  });

  it("sessions_spawn is NOT in deny list", () => {
    const denied = config.tools.deny || [];
    assert.ok(
      !denied.includes("sessions_spawn"),
      "sessions_spawn must NOT be denied — sub-agents need it",
    );
  });

  it("subagents.maxConcurrent >= 1", () => {
    assert.ok(
      config.agents.defaults.subagents.maxConcurrent >= 1,
      "maxConcurrent must be >= 1 for sub-agents to work",
    );
  });
});
